config/routes.rb
Rails.application.routes.draw do
  resources :authentications
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	devise_scope :user do
		authenticated :user do
			root 'user#index'
		end
		unauthenticated :user do
			root :to => 'devise/registrations#new', as: :unauthenticated_root
		end
	end

	resources :user do
		get :make_moderator
		get :make_normal_user
		delete 'user/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
		get 'user/:id' => 'user#show'
	end
	resources :landings

end

app/models/landing.rb
class Landing < ActiveRecord::Base
	
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create
  before_action :set_landing, only: [:show, :edit, :update, :destroy]
  layout 'home', only: [:index, :update, :destroy]
  layout 'admin_lte_2', only: [:show]
  # GET /landings
  # GET /landings.json
  def index
    # @landings = Landing.all
    @landing = Landing.new
  end

  # GET /landings/1
  # GET /landings/1.json
  def show
  end

  # GET /landings/new
  def new
    @landing = Landing.new
  end

  # GET /landings/1/edit
  def edit
  end

  # POST /landings
  # POST /landings.json
  def create
    
    @landing = Landing.new(landing_params)

    respond_to do |format|
      if @landing.save
          format.html { redirect_to @landing, notice: 'Landing was successfully created.' }
          format.json { render :show, status: :created, location: @landing }
      else
        format.html { render :new }
        format.json { render json: @landing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /landings/1
  # PATCH/PUT /landings/1.json
  def update
    respond_to do |format|
      if @landing.update(landing_params)
        format.html { redirect_to @landing, notice: 'Landing was successfully updated.' }
        format.json { render :show, status: :ok, location: @landing }
      else
        format.html { render :edit }
        format.json { render json: @landing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landings/1
  # DELETE /landings/1.json
  def destroy
    @landing.destroy
    respond_to do |format|
      format.html { redirect_to landings_url, notice: 'Landing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_user_with_twitter_login
    # byebug
    if  current_user.authentications.empty?
        false
      else
        true
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landing
      @landing = Landing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landing_params
      params.require(:landing).permit(:search)
    end
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/_form.html.haml
/ %form.form-inline{:action => "in", :method => "post"}
/   .form-group
/     %input#formGroupExampleInput.form-control.input-lg{:placeholder => "Type a #tag", :type => "text"}
/   %button.btn.btn-primary.btn-xl{:type => "submit"} Analyze

= form_for @landing, remote: true,  :html => {:class =>  "form-inline" }do |f|
  - if @landing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@landing.errors.count, "error")} prohibited this landing from being saved:"
      %ul
        - @landing.errors.full_messages.each do |msg|
          %li= msg
 
  = f.text_field :search,:placeholder => "Type a #tag", :type => "text", :input_html => {:maxlength =>100,:style=> 'width: 300px'},  label: false, class: "formGroupExampleInput form-control input-lg"
  
  = f.button :Analyze, :value => "submit", :type => "submit", class: "btn btn-primary btn-xl"

= link_to 'Click Here', "#", data: {toggle: "modal", target: "#modal"}

app/views/landings/edit.html.haml
%h1 Editing landing

= render 'form'

= link_to 'Show', @landing
\|
= link_to 'Back', landings_path

app/views/landings/index.html.haml
= render 'form'

app/views/landings/new.html.haml
= render 'form'

app/views/landings/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_landing_path(@landing)
\|
= link_to 'Back', landings_path