config/routes.rb
Rails.application.routes.draw do
  resources :authentications
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	devise_scope :user do
		authenticated :user do
			root 'user#index'
		end
		unauthenticated :user do
			root :to => 'devise/registrations#new', as: :unauthenticated_root
		end
	end

	resources :user do
		get :make_moderator
		get :make_normal_user
		delete 'user/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
		get 'user/:id' => 'user#show'
	end
	resources :landings

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user


	def self.find_for_oauth(auth, provider_type)
	    unless authentication = self.find_by(uid: auth[:uid].to_s, provider_type: provider_type)
	      user = User.find_by_email(auth[:info][:email])
	      authentication = user.authentications.where(provider_type: provider_type).first if user.present?
	      authentication ||= Authentication.new
	    end
	    authentication.update_from_oauth(auth, provider_type)
	    authentication
	  end

	def update_from_oauth(auth, provider_type)
		self.email= auth[:info][:email]
		self.uid= auth[:uid]
		self.provider_type= provider_type
		credentials = auth[:credentials]
		
		case provider_type
			when :twitter
			  self.token = credentials[:token]
			  self.token_secret = credentials[:secret]
			  self.url = auth[:info][:urls][:Twitter]
			# when :facebook
			#   ...
			# when :google
			#   ...
			end
	end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  before_action :set_authentication, only: [:show, :edit, :update, :destroy]

  # GET /authentications
  # GET /authentications.json
  def index
    @authentications = Authentication.all
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
  end

  # GET /authentications/new
  def new
    @authentication = Authentication.new
  end

  # GET /authentications/1/edit
  def edit
  end

  # POST /authentications
  # POST /authentications.json
  def create
    @authentication = Authentication.new(authentication_params)

    respond_to do |format|
      if @authentication.save
        format.html { redirect_to @authentication, notice: 'Authentication was successfully created.' }
        format.json { render :show, status: :created, location: @authentication }
      else
        format.html { render :new }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authentications/1
  # PATCH/PUT /authentications/1.json
  def update
    respond_to do |format|
      if @authentication.update(authentication_params)
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { render :show, status: :ok, location: @authentication }
      else
        format.html { render :edit }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication.destroy
    respond_to do |format|
      format.html { redirect_to authentications_url, notice: 'Authentication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authentication
      @authentication = Authentication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authentication_params
      params.require(:authentication).permit(:user_id, :povider, :uid)
    end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.haml
= form_for @authentication do |f|
  - if @authentication.errors.any?
    #error_explanation
      %h2= "#{pluralize(@authentication.errors.count, "error")} prohibited this authentication from being saved:"
      %ul
        - @authentication.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :povider
    = f.text_field :povider
  .field
    = f.label :uid
    = f.text_field :uid
  .actions
    = f.submit 'Save'

app/views/authentications/edit.html.haml
%h1 Editing authentication

= render 'form'

= link_to 'Show', @authentication
\|
= link_to 'Back', authentications_path

app/views/authentications/index.html.haml
%h1 Listing authentications

%table
  %thead
    %tr
      %th User
      %th Povider
      %th Uid
      %th
      %th
      %th

  %tbody
    - @authentications.each do |authentication|
      %tr
        %td= authentication.user_id
        %td= authentication.povider
        %td= authentication.uid
        %td= link_to 'Show', authentication
        %td= link_to 'Edit', edit_authentication_path(authentication)
        %td= link_to 'Destroy', authentication, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Authentication', new_authentication_path

app/views/authentications/new.html.haml
%h1 New authentication

= render 'form'

= link_to 'Back', authentications_path

app/views/authentications/show.html.haml
%p#notice= notice

%p
  %b User:
  = @authentication.user_id
%p
  %b Povider:
  = @authentication.povider
%p
  %b Uid:
  = @authentication.uid

= link_to 'Edit', edit_authentication_path(@authentication)
\|
= link_to 'Back', authentications_path