config/routes.rb
Rails.application.routes.draw do
  resources :authentications
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	devise_scope :user do
		authenticated :user do
			root 'user#index'
		end
		unauthenticated :user do
			root :to => 'devise/registrations#new', as: :unauthenticated_root
		end
	end

	resources :user do
		get :make_moderator
		get :make_normal_user
		delete 'user/:id' => 'user#destroy', :via => :delete #, :as => :admin_destroy_user
		get 'user/:id' => 'user#show'
	end
	resources :landings

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:twitter]
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  belongs_to :role
  before_create :set_default_role
  has_many :authentications, dependent: :destroy

  extend FriendlyId
    friendly_id :full_names, use: :slugged


  #******************Omniauth********************#
  # def self.from_omniauth(auth, provider_type)
  #   self.email = auth[:info][:email] if self.email.blank?
  #   case provider_type
  #     when :twitter
  #       name = auth[:info][:name].split(' ')
  #       self.first_name ||= name[0]
  #       self.last_name ||= name[1]
  #       self.avatar = auth.info.image

  #   # where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #   #   user.email = auth.info.email
  #   #   byebug
  #   #   user.password = Devise.friendly_token[0,20]
  #   #   user.first_name = auth.info.name   # assuming the user model has a name
  #   #   user.avatar = auth.info.image # assuming the user model has an image
  #   end
  # end

  def update_from_oauth(auth, provider_type)
    self.email = auth[:info][:email] if self.email.blank?
    case provider_type
    when :twitter
      name = auth[:info][:name].split(' ')
      self.first_name ||= name[0]
      self.last_name ||= name[1]
      # self.remote_avatar_url = auth[:extra][:raw_info][:profile_image_url]
      self.avatar = auth.info.image

    # when :facebook
    #   ...
    # when :google
    #   ...
    end
  end
  #********************End************************#

 
#*******************User Admin Methods************#

  def is_admin?
  	if self.role.nil?
  		false
  	elsif self.role.name == "admin"
  		true
  	else
  		false
  	end
  end

  def full_names
  	first = self.first_name
  	last = self.last_name
  	 "#{first} #{last}"
  end

  def is_moderator?
  	if self.role.nil?
  		false
  	elsif self.role.name == "moderator"
  		true
  	else
  		false
  	end
  end

  def has_admin_previlages?
  	if is_admin? || is_moderator?
  		true
  	else
  		false
  	end
  end

  def make_moderator
  	self.update_attributes :role_id => 3
  	# self.role ||= Role.find_by_name('moderator') 
  end

  def make_admin
  	self.update_attributes :role_id => 4
  end

  def make_normal_user
  	self.update_attributes :role_id => 1
  end

  def show_admins
  	User.where(:role_id => 4 )
  end
#*******************End of User Admin Methods************#

	private
	
	def set_default_role
		self.role ||= Role.find_by_name('registered') 
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    data = []
    lables = User.group_by_month(:created_at).count
    @data = {
      labels: lables.map {|label, data| label.strftime("%B") },
      datasets: [
        {
           # label: "My First dataset",
           # pointStrokeColor: "#FFA500",
           # fillColor: "rgba(255,165,0,0.5)",
           # pointColor: "rgba(255,165,0,1)",
           # strokeColor: "rgba(255,165,0,1)",
           data: lables.map {|label, data| data  },
           backgroundColor: "#FF6384",
           hoverBackgroundColor: "#FF6384"

        }
      ]
    }
    @options = {:height => "253", :width => "507"}
    # byebug

    @data2 = {
      labels: lables.map {|label, data| label.strftime("%B") },
      datasets: [
        {
           label: "My First dataset",
           pointStrokeColor: "#FFA500",
           fillColor: "rgba(255,165,0,0.5)",
           pointColor: "rgba(255,165,0,1)",
           strokeColor: "rgba(255,165,0,1)",
           data: lables.map {|label, data| data  },
           # backgroundColor: "#FF6384",
           # hoverBackgroundColor: "#FF6384"

        }
      ]
    }
    @options1 = {:height => "253", :width => "507"}
    @options2 = {:height => "253", :width => "507"}
    @options3 = {:height => "253", :width => "507"}
    @options4 = {:height => "253", :width => "507"}
    @options5 = {:height => "253", :width => "507"}
    # byebug
  end

  # GET /users/1
  # GET /users/1.json
  def show
    byebug
    @user = User.friendly.find(params[:id])

    @twitter_username = request.env["omniauth.auth"]["info"]["nickname"]
    @user_name = request.env["omniauth.auth"]["info"]["name"]
    @twitter_avatar_url = request.env["omniauth.auth"]["info"]["image"]

    @oauth_token = request.env["omniauth.auth"]["extra"]["access_token"].params[:oauth_token]
    @oauth_token_secret = request.env["omniauth.auth"]["extra"]["access_token"].params[:oauth_token_secret]

    @timeline = Timeline.new(@oauth_token, @oauth_token_secret)

    @url_objs = @timeline.make_url_objs
    @max_appearances = @timeline.get_max_appearances(@url_objs)
    byebug
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.friendly.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def make_moderator
    @user = User.find(params[:user_id])
    @user.make_moderator
    respond_to do |format|
      format.html { redirect_to user_index_path, notice:  " #{@user.first_name} is now a Moderator." }
      format.json { head :no_content }
    end
  end
  def make_normal_user
    @user = User.find(params[:user_id])
    @user.make_normal_user
    respond_to do |format|
      format.html { redirect_to user_index_path, notice:  " #{@user.first_name} is now a Normal User." }
      format.json { head :no_content }
    end
  end



  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to user_index_path, notice:  " #{@user.first_name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      byebug
      params.require(:user).permit(:avatar)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # def twitter
  #   # You need to implement the method below in your model (e.g. app/models/user.rb)
  #   @user = User.from_omniauth(request.env["omniauth.auth"])

  #   if @user.persisted?
  #     sign_in_and_redirect user_index_path #, :event => :authentication #this will throw if @user is not activated
  #     set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
  #   else
  #     session["devise.twitter_data"] = request.env["omniauth.auth"]
  #     # redirect_to new_user_registration_url
  #     redirect_to user_index_path
  #     set_flash_message(:notice, :success, :kind => "Twitter")
  #   end
  # end

  # def failure
  #   redirect_to root_path
  # end

  before_filter :prepare_auth

  def facebook
    connect(:facebook)
  end

  def twitter
    connect(:twitter)
  end

  def google_oauth2
    connect(:google)
  end

  private

    def prepare_auth
      @auth = request.env["omniauth.auth"]
    end

    def connect(provider_type)
        authentication = Authentication.find_for_oauth(@auth, provider_type)
        
        if user_signed_in?
          if authentication and authentication.user_id == current_user.id
            flash[:notice] = "Your #{provider_type} account is already attached"
            redirect_to current_user and return
          elsif authentication.user_id.nil?
            current_user.update_from_oauth(@auth, provider_type)
            current_user.authentications << authentication if current_user.save
            flash[:notice] = "Successfully attached #{provider_type} account"
            redirect_to current_user and return
          else
            flash[:notice] = "#{provider_type} is already connected to another account"
            redirect_to current_user and return
          end
        else
          byebug

          #If the user already exists or can be found by email provided in auth hash  if not create a new user.
          @user = authentication.user || User.find_by_email(@auth[:info][:email])|| User.new

          #If the auth doesn't have an email in the hash
          @authentication = Authentication.find_by_uid(@auth[:uid])
          @user.update_from_oauth(@auth, provider_type)
          authentication.save
          byebug
          if @user.persisted? # If user already has account and not logged in
            @user.authentications << authentication if @user.save
            flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => provider_type.capitalize
            sign_in_and_redirect @user, :event => :authentication
          elsif authentication.user.nil?
            @user = User.new
            @user.update_from_oauth(@auth, provider_type)
            @user.email = "#{@user.first_name}@gmail.com"
            @user.authentications << authentication if @user.save
            flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => provider_type.capitalize
            sign_in_and_redirect @user, :event => :authentication
            byebug
          else # If user has no account
            session[:sp_id] = authentication.id 
            redirect_to new_user_registration_url
          end
        end
      end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/_form.html.haml
= form_for @user, :html => {:class => 'form-horizontal'} do |f|
  %form.form-horizontal
    - if @user.errors.any?
      #error_explanation
        %h2
          = pluralize(@user.errors.count, "error")
          prohibited this user from being saved:
        %ul
          - @user.errors.full_messages.each do |message|
            %li= message

    .form-group
      %label.col-sm-2.control-label{:for => "inputName"} First Name
      .col-sm-10
        = f.text_field :first_name, class: "form-control", :placeholder => "First Name"
    .form-group
      %label.col-sm-2.control-label{:for => "inputName"} Last Name
      .col-sm-10
        = f.text_field :last_name, class: "form-control", :placeholder => "Last Name"
    .form-group
      %label.col-sm-2.control-label{:for => "inputEmail"} Email
      .col-sm-10
        = f.text_field :email, class: "form-control", :placeholder => "Email"
    .form-group
      %label.col-sm-2.control-label{:for => "password"} Password
      .col-sm-10
        = f.text_field :password, class: "form-control", :placeholder => "Password"
    .form-group
      .col-sm-offset-2.col-sm-10
        .checkbox
          %label
            %input{:type => "checkbox"}
              I agree to the
              %a{:href => "#"} terms and conditions
    .box-body
      .form-group
        %label{:for => "exampleInputFile"} File input
        = f.file_field :avatar
        %p.help-block Example block-level help text here

    .form-group
      .col-sm-offset-2.col-sm-10
        / %button.btn.btn-danger{:type => "submit"} Submit
        = f.submit 'Update', class: 'btn btn-danger'

app/views/user/_table.html.haml
.col-xs-12
  .box
    .box-header
      %h3.box-title Registered Users
      .box-tools
        .input-group.input-group-sm{:style => "width: 150px;"}
          %input.form-control.pull-right{:name => "table_search", :placeholder => "Search", :type => "text"}
            .input-group-btn
              %button.btn.btn-default{:type => "submit"}
                %i.fa.fa-search
    / /.box-header
    .box-body.table-responsive.no-padding
      %table.table.table-hover
        %tbody
          %tr
            %th Full Names
            %th Email
            %th settings
        - users.each do |user|
          %tr
            %td= user.full_names
            %td= user.email
            %td
              -if current_user && current_user.is_admin?
                = link_to 'Show Details',  user, class: "label label-warning"
                
                -unless current_user == user
                  = link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "label label-danger"
                  -if user.is_moderator?
                    = link_to " Moderator - Make Normal user", user_make_normal_user_path(user), class: "label label-pill label-default"
                  -elsif user.is_admin?
                    = link_to " Admin Make Normal user",  user_make_normal_user_path(user), :data => { :confirm => 'Are you sure?' }, class: "label label-pill label-info"
                  -else
                    = link_to "Make moderator", user_make_moderator_path(user), :data => { :confirm => 'Are you sure?' }, class: "label label-success"

.row
  .col-md-6
    .box.box-danger
      .box-header.with-border
        %h3.box-title Pie Chart
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        = pie_chart @data, @options

  .col-md-6
    .box.box-danger
      .box-header.with-border
        %h3.box-title Donut Chart
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        = doughnut_chart @data, @options1


  .col-md-6
    .box.box-success
      .box-header.with-border
        %h3.box-title Line Chart
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        = line_chart @data, @options2

  .col-md-6
    .box.box-success
      .box-header.with-border
        %h3.box-title Polar Chart
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        = polar_area_chart @data, @options3

  .col-md-6
    .box.box-success
      .box-header.with-border
        %h3.box-title Radar Chart
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        = radar_chart @data, @options4

  .col-md-6
    .box.box-success
      .box-header.with-border
        %h3.box-title Bar Chart
        .box-tools.pull-right
          %button.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
            %i.fa.fa-minus
          %button.btn.btn-box-tool{"data-widget" => "remove", :type => "button"}
            %i.fa.fa-times
      .box-body
        = bar_chart @data, @options5

app/views/user/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
\#{link_to 'Back', user_index_path}

app/views/user/index.html.haml
%p#notice= notice
= render "user/table", users: @users
%br
  = link_to 'New User', new_user_path

app/views/user/new.html.haml
%h1 New User
= render 'form'
= link_to 'Back', user_index_path

app/views/user/show.html.haml
%p#notice= notice


.col-md-3
  / Profile Image
  .box.box-primary
    .box-body.box-profile
      %img.profile-user-img.img-responsive.img-circle{:alt => "User profile picture", :src => "#{@user.avatar.url}"}
        %h3.profile-username.text-center 
          =@user.full_names
        %p.text-muted.text-center Software Engineer
        %ul.list-group.list-group-unbordered
          %li.list-group-item
            %b Followers
            %a.pull-right 1,322
          %li.list-group-item
            %b Following
            %a.pull-right 543
          %li.list-group-item
            %b Friends
            %a.pull-right 13,287
        %a.btn.btn-primary.btn-block{:href => "#"}
          %b Follow
    / /.box-body
  / /.box
  / About Me Box
  / .box.box-primary
  /   .box-header.with-border
  /     %h3.box-title About Me
  /   / /.box-header
  /   .box-body
  /     %strong
  /       %i.fa.fa-book.margin-r-5
  /       Education
  /     %p.text-muted
  /       B.S. in Computer Science from the University of Tennessee at Knoxville
  /     %hr
  /       %strong
  /         %i.fa.fa-map-marker.margin-r-5
  /         Location
  /       %p.text-muted Malibu, California
  /       %hr
  /         %strong
  /           %i.fa.fa-pencil.margin-r-5
  /           Skills
  /         %p
  /           %span.label.label-danger UI Design
  /           %span.label.label-success Coding
  /           %span.label.label-info Javascript
  /           %span.label.label-warning PHP
  /           %span.label.label-primary Node.js
  /         %hr
  /           %strong
  /             %i.fa.fa-file-text-o.margin-r-5
  /             Notes
  /           %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.


.col-md-9
  .nav-tabs-custom
    %ul.nav.nav-tabs
      %li.active
        %a{"aria-expanded" => "true", "data-toggle" => "tab", :href => "#activity"} Activity
      %li
        %a{"aria-expanded" => "false", "data-toggle" => "tab", :href => "#timeline"} Timeline
      %li
        %a{"aria-expanded" => "false", "data-toggle" => "tab", :href => "#settings"} Settings
    .tab-content
      #activity.tab-pane.active
        / Post
        .post
          .user-block
            %img.img-circle.img-bordered-sm{:alt => "user image", :src => "../../dist/img/user1-128x128.jpg"}
              %span.username
                %a{:href => "#"} Jonathan Burke Jr.
                %a.pull-right.btn-box-tool{:href => "#"}
                  %i.fa.fa-times
              %span.description Shared publicly - 7:30 PM today
          / /.user-block
          %p
            Lorem ipsum represents a long-held tradition for designers,
            typographers and the like. Some people hate it and argue for
            its demise, but others ignore the hate as they create awesome
            tools to help create filler text for everyone from bacon lovers
            to Charlie Sheen fans.
          %ul.list-inline
            %li
              %a.link-black.text-sm{:href => "#"}
                %i.fa.fa-share.margin-r-5
                Share
            %li
              %a.link-black.text-sm{:href => "#"}
                %i.fa.fa-thumbs-o-up.margin-r-5
                Like
            %li.pull-right
              %a.link-black.text-sm{:href => "#"}
                %i.fa.fa-comments-o.margin-r-5
                Comments
                (5)
          %input.form-control.input-sm{:placeholder => "Type a comment", :type => "text"}
        / /.post
        / Post
        .post.clearfix
          .user-block
            %img.img-circle.img-bordered-sm{:alt => "User Image", :src => "../../dist/img/user7-128x128.jpg"}
              %span.username
                %a{:href => "#"} Sarah Ross
                %a.pull-right.btn-box-tool{:href => "#"}
                  %i.fa.fa-times
              %span.description Sent you a message - 3 days ago
          / /.user-block
          %p
            Lorem ipsum represents a long-held tradition for designers,
            typographers and the like. Some people hate it and argue for
            its demise, but others ignore the hate as they create awesome
            tools to help create filler text for everyone from bacon lovers
            to Charlie Sheen fans.
          %form.form-horizontal
            .form-group.margin-bottom-none
              .col-sm-9
                %input.form-control.input-sm{:placeholder => "Response"}
              .col-sm-3
                %button.btn.btn-danger.pull-right.btn-block.btn-sm{:type => "submit"} Send
        / /.post
        / Post
        .post
          .user-block
            %img.img-circle.img-bordered-sm{:alt => "User Image", :src => "../../dist/img/user6-128x128.jpg"}
              %span.username
                %a{:href => "#"} Adam Jones
                %a.pull-right.btn-box-tool{:href => "#"}
                  %i.fa.fa-times
              %span.description Posted 5 photos - 5 days ago
          / /.user-block
          .row.margin-bottom
            .col-sm-6
              %img.img-responsive{:alt => "Photo", :src => "../../dist/img/photo1.png"}
            / /.col
            .col-sm-6
              .row
                .col-sm-6
                  %img.img-responsive{:alt => "Photo", :src => "../../dist/img/photo2.png"}
                    %br
                      %img.img-responsive{:alt => "Photo", :src => "../../dist/img/photo3.jpg"}
                / /.col
                .col-sm-6
                  %img.img-responsive{:alt => "Photo", :src => "../../dist/img/photo4.jpg"}
                    %br
                      %img.img-responsive{:alt => "Photo", :src => "../../dist/img/photo1.png"}
                / /.col
              / /.row
            / /.col
          / /.row
          %ul.list-inline
            %li
              %a.link-black.text-sm{:href => "#"}
                %i.fa.fa-share.margin-r-5
                Share
            %li
              %a.link-black.text-sm{:href => "#"}
                %i.fa.fa-thumbs-o-up.margin-r-5
                Like
            %li.pull-right
              %a.link-black.text-sm{:href => "#"}
                %i.fa.fa-comments-o.margin-r-5
                Comments
                (5)
          %input.form-control.input-sm{:placeholder => "Type a comment", :type => "text"}
        / /.post
      / /.tab-pane
      #timeline.tab-pane
        / The timeline
        %ul.timeline.timeline-inverse
          / timeline time label
          %li.time-label
            %span.bg-red
              10 Feb. 2014
          / /.timeline-label
          / timeline item
          %li
            %i.fa.fa-envelope.bg-blue
            .timeline-item
              %span.time
                %i.fa.fa-clock-o
                12:05
              %h3.timeline-header
                %a{:href => "#"} Support Team
                sent you an email
              .timeline-body
                Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles,
                weebly ning heekya handango imeem plugg dopplr jibjab, movity
                jajah plickers sifteo edmodo ifttt zimbra. Babblely odeo kaboodle
                quora plaxo ideeli hulu weebly balihoo...
              .timeline-footer
                %a.btn.btn-primary.btn-xs Read more
                %a.btn.btn-danger.btn-xs Delete
          / END timeline item
          / timeline item
          %li
            %i.fa.fa-user.bg-aqua
            .timeline-item
              %span.time
                %i.fa.fa-clock-o
                5 mins ago
              %h3.timeline-header.no-border
                %a{:href => "#"} Sarah Young
                accepted your friend request
          / END timeline item
          / timeline item
          %li
            %i.fa.fa-comments.bg-yellow
            .timeline-item
              %span.time
                %i.fa.fa-clock-o
                27 mins ago
              %h3.timeline-header
                %a{:href => "#"} Jay White
                commented on your post
              .timeline-body
                Take me to your leader!
                Switzerland is small and neutral!
                We are more like Germany, ambitious and misunderstood!
              .timeline-footer
                %a.btn.btn-warning.btn-flat.btn-xs View comment
          / END timeline item
          / timeline time label
          %li.time-label
            %span.bg-green
              3 Jan. 2014
          / /.timeline-label
          / timeline item
          %li
            %i.fa.fa-camera.bg-purple
            .timeline-item
              %span.time
                %i.fa.fa-clock-o
                2 days ago
              %h3.timeline-header
                %a{:href => "#"} Mina Lee
                uploaded new photos
              .timeline-body
                %img.margin{:alt => "...", :src => "http://placehold.it/150x100"}
                  %img.margin{:alt => "...", :src => "http://placehold.it/150x100"}
                    %img.margin{:alt => "...", :src => "http://placehold.it/150x100"}
                      %img.margin{:alt => "...", :src => "http://placehold.it/150x100"}
          / END timeline item
          %li
            %i.fa.fa-clock-o.bg-gray
      / /.tab-pane
      #settings.tab-pane
        = render 'form'
      / /.tab-pane
    / /.tab-content
  / /.nav-tabs-custom

= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', user_index_path}